### PR TITLE
stream file fix

### PR DESCRIPTION
**Pull request by tanner0101**
Potential fix for https://github.com/vapor/vapor/issues/1801.

Fixes an issue where connection would be closed before chunked body is finished streaming.

### CODE REVIEW

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 876 coins.

**Comment by foscomputerservices** [comment]
Just curious, are there any plans to implement CI tests for this issue?  Maybe I missed something in the change log, but I didn't notice any tests added along with the bug fix.

This bug caused our production website to be unusable for 3 days and caused much consternation with customers during this time (they are paying for our service).  I also spent a weekend thinking that I had broken something in the container/load balancer/nginx configuration.

The problem is that I use 'vapor update' (or swift package update) to pick up changes in my own packages, which also updates vapor and its dependencies.

I suppose I could pin all of the vapor dependencies and hand-test everything before pulling updates, but I was under the impression that there were tests for most of Vapor (especially at the lowest levels) due to the Circle CI passing badge.  However, when I dig into the tests, there doesn't seem to be much there.  Maybe I'm missing something?

I do realize that vapor is open source and I could contribute tests as well, and if I can find some spare cycles I just might do that.  I'm mostly wondering what we can expect for stability from these lowest-level libraries as I was a bit dismayed when I see a PR with no unit/regression tests validating the new functionality. (https://github.com/vapor/http/pull/306/files)

**Comment by tanner0101** [comment]
Hey @foscomputerservices, first off I'm really sorry for the issues that bug caused you. This bug is particularly annoying to test because of the amount of layers involved. We figured it would be easier for this one to add the tests into Vapor itself since we can use the higher level abstractions of FileMiddleware and Vapor's clients to test the edge cases. As a part of vapor/http's CI tests, we build and run Vapor's tests with the updates from HTTP checked out to ensure nothing breaks there. 

That said, we have been really busy and haven't added those tests in Vapor yet. The priority was to get this fix out ASAP. But I will make sure we get them in there.

**Comment by foscomputerservices** [comment]
@tanner0101 , thanks for the response, it means a lot.  We really love vapor and know there will be hiccups along the way when we're on the bleeding edge.  Keep up the great work!

**Pull request merged**
