### PR TITLE
unclean shutdown test

### PR DESCRIPTION
**Pull request by tanner0101**

### CODE REVIEW

**Comment by tanner0101** [comment]
Related to https://github.com/vapor/http/issues/284

**Comment by tanner0101** [comment]
@MrMage after discussing with NIO guys, they seem to believe this is caused by Amazon (in the case of the failing test here) and not Vapor/NIO.

**Comment by MrMage** [comment]
But my test connects to Google Cloud Platform, not AWS? I have a hard time believing that _both_ providers are doing something non-standard here, and I'm convinced that we could probably find several more examples with just a bit of searching.

**Comment by tanner0101** [comment]
This was fixed in #326

**Pull request closed without merging**
